---
exclude: '^(build|docs)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: ['pydocstyle[toml]']
        files: src

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^(tests/|e2e_test/)

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: tflint
      - id: terraform-fmt

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_tfsec

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-infra
        args: ["markdown", "table", "--output-file", "./README.md", "--output-mode", "inject", "--recursive", "terraform/infra"]
      - id: terraform-docs-go
        name: terraform-docs-endpoints
        args: ["markdown", "table", "--output-file", "./README.md", "--output-mode", "inject", "terraform/endpoints"]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        files: \.py$
        stages: [commit]
        language: system
        entry: pyright
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: ^(dev/|terraform/)
        args:
          [
            "-rn",  # Only display messages
            "-sn",  # Don't display the score
          ]
